[package]
name = "di-cli"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs-next = "*"
thiserror="*"
log = "*"
env_logger = "*"
git2 = "*"
termcolor = "*"
which = "*"
serde = { version = "*", features = ["derive"] }
tempdir = "*"
filename = "*"
diff = "*"

[dependencies.clap]
version = "2.31.2"
features = ["suggestions", "color", "wrap_help"]

[profile.release]
lto = true
codegen_units = 1
